language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - export PATH="${PATH}:/usr/local/bin"
  - docker -v && docker-compose -v
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - cp config ${HOME}/.kube/config
  - echo $PATH
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
  - chmod +x ./aws-iam-authenticator
  - sudo cp ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
  - mkdir ${HOME}/.aws/
  - cp ./aws ${HOME}/.aws/credentials
  - kubectl get all
  - mkdir ${HOME}/.docker
  - cp ./needed.json ${HOME}/.docker/config.json

install:
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build
  - echo $TRAVIS_JOB_ID
  - docker tag lalitcoder05/reverseproxy:latest lalitcoder05/reverseproxy:${TRAVIS_JOB_ID}
  - docker tag lalitcoder05/udacity-restapi-feed:latest lalitcoder05/udacity-restapi-feed:${TRAVIS_JOB_ID}
  - docker tag lalitcoder05/udacity-restapi-user:latest lalitcoder05/udacity-restapi-user:${TRAVIS_JOB_ID}
  - docker tag lalitcoder05/udacity-frontend:latest lalitcoder05/udacity-frontend:${TRAVIS_JOB_ID}
  - docker push lalitcoder05/reverseproxy:${TRAVIS_JOB_ID}
  - docker push lalitcoder05/udacity-restapi-feed:${TRAVIS_JOB_ID}
  - docker push lalitcoder05/udacity-restapi-user:${TRAVIS_JOB_ID}
  - docker push lalitcoder05/udacity-frontend:${TRAVIS_JOB_ID}
  - kubectl rolling-update reverseproxy --image=lalitcoder05/reverseproxy:${TRAVIS_JOB_ID}
  - kubectl rolling-update udacity-restapi-feed --image=lalitcoder05/udacity-restapi-feed:${TRAVIS_JOB_ID}
  - kubectl rolling-update udacity-restapi-user --image=lalitcoder05/udacity-restapi-user:${TRAVIS_JOB_ID}
  - kubectl rolling-update udacity-frontend --image=lalitcoder05/udacity-frontend:${TRAVIS_JOB_ID}

