apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy
#  externalTrafficPolicy: Local
  type: LoadBalancer    
