version: "3"
services:
  reverseproxy:
      image: lalitcoder05/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: lalitcoder05/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: 12345678 
      POSTGRESS_DB: feed
      POSTGRESS_HOST: feed.cxz4jkxv8kjj.us-east-2.rds.amazonaws.com 
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: static-website-udacityproject
      JWT_SECRET: coderlalit
      URL: "http://localhost:8100"
  backend-feed:
    image: lalitcoder05/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: 12345678 
      POSTGRESS_DB: feed
      POSTGRESS_HOST: feed.cxz4jkxv8kjj.us-east-2.rds.amazonaws.com 
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: static-website-udacityproject
      JWT_SECRET: coderlalit
      URL: "http://localhost:8100"
  frontend:
    image: lalitcoder05/udacity-frontend
    ports:
      - "8100:80"
